### ISSUE TITLE
`RuntimeDependency`'s `compat` entry missing from `Project.toml`

### ISSUE THREAD

**Issue by omus** [JuliaPackaging/BinaryBuilder.jl#1330]
> The optional keyword argument `compat` can be used to specify a string for use in the `Project.toml` of the generated Julia package.

– https://docs.binarybuilder.org/stable/reference/#BinaryBuilderBase.RuntimeDependency

I was trying to add a `RuntimeDependency` for [`pandoc_crossref`](https://github.com/JuliaPackaging/Yggdrasil/blob/master/P/pandoc_crossref/build_tarballs.jl) and have found that the `compat` entry is ignored.

Specifically I added:
```julia
RuntimeDependency(PackageSpec(name="pandoc_jll"), compat="=3.2.0")
```
and then ran:
```sh
julia build_tarballs.jl --verbose --deploy=local x86_64-linux-gnu && cat ~/.julia/dev/pandoc_crossref_jll/Project.toml
```
Which resulted in this `Project.toml`:
```toml
name = "pandoc_crossref_jll"
uuid = "f96e3c25-ae70-5588-8d8e-4a7ab3ba4c45"
version = "0.3.17+1"

[deps]
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
pandoc_jll = "c5432543-76ad-5c9d-82bf-db097047a5e2"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"

[compat]
JLLWrappers = "1.2.0"
julia = "1.6"
Libdl = "1"
Artifacts = "1"
```
