### ISSUE TITLE
Add support for meson build system

### ISSUE THREAD

**Issue by giordano** [JuliaPackaging/BinaryBuilder.jl#437]
Building software with [meson](https://mesonbuild.com) requires writing a text file like this (see https://mesonbuild.com/Cross-compilation.html):

```toml
[binaries]
c = '${CC}'
cpp = '${CXX}'
ar = '${AR}'
strip = '${STRIP}'
pkgconfig = '/usr/bin/pkg-config'

[properties]
c_args = ['-I$prefix/include']
c_link_args = ['-L${prefix}/lib']
cpp_args = ['-I$prefix/include']
cpp_link_args = ['-L${prefix}/lib']

[host_machine]
system = 'linux'
cpu_family = 'x86_64'
cpu = 'i686'
endian = 'little'

[target_machine]
system = 'linux'
cpu_family = 'x86_64'
cpu = 'i686'
endian = 'little'

[paths]
prefix = '${prefix}'
libdir = 'lib'
bindir = 'bin'
```

This could be sitting in `/opt/${target}/${target}_meson_cross_file.txt` (or somehting like that), next to the CMake toolchain file.

These tables can be useful: https://github.com/mesonbuild/meson/blob/4ebce2c3f25d98f9ba49d9fcc343ffbe760363af/docs/markdown/Reference-tables.md.

For the value of `cpu` the function `detect_cpu` here https://github.com/mesonbuild/meson/blob/4ebce2c3f25d98f9ba49d9fcc343ffbe760363af/mesonbuild/environment.py#L280 should be useful.
