### ISSUE TITLE
Store more metadata in JLL packages

### ISSUE THREAD

**Issue by staticfloat** [JuliaPackaging/BinaryBuilder.jl#639]
I think we need to start storing more metadata within tarballs/JLL packages.  In particular, I think the following list of things would be nice to store:

* BB version+gitsha used for build: useful for build caching
* hash of source build recipe: useful for build caching
* Source URLs: useful for GPL compliance
* Source licenses (the contents of `share/licenses/${src_name}/`): useful for GPL compliance

We should store these in the tarballs, but also in the JLL package itself, for easy inspection.

**Comment by giordano** [comment]
I think this has been partially addressed by #794, at least as long as the README of the JLL packages is concerned

**Comment by fingolfin** [comment]
More things:
- homepage of the project being wrapped
- a short description of what it is / does
- possibly information about maintainers (of the JLL)?!? I.e. "whom should I contact if I have trouble with this JLL" (not sure how useful this really is, though, perhaps people should just submit Yggdrasil issues and we'll sort it out based on the git log of a given recipe?)

**Comment by giordano** [comment]
Other things I believe might be good to add to a metadata file:

* list of all products, for all platforms, with the name with which we dlopen it.  I think that having it could help us address https://github.com/JuliaLang/julia/issues/40556 if we use in `DT_NEEDED` the `dlopen` name of the needed lib
* list of `BuildDependency`s (per platform, even if the same for all platforms).  In this way we can propagate build dependencies, which are lost in the registry

**Comment by fingolfin** [comment]
So, to get a bit more specific: how would we store those? Perhaps as a `meta.json` file, which is added into the JLL repository, and then we can just (de-)serialize a suitable Dict with whatever keys we want. That should make it easy to add/remove keys.

Does that seem OK? Is JSON fine? If not what else? Should the file be called something else?

Next, we need to get the data: Some of it we can fill in automatically:
- BB version+gitsha used for build
- hash of source build recipe
- Source URLs
- list of all products, for all platforms, with the name with which we dlopen it
- list of BuildDependencys (per platform, even if the same for all platforms), presumably including version/compat restrictions
- version number of toolchains

Some must be provided by the user / passed to `build_tarballs`
- license, e.g. an SPDX identifier
- upstream homepage
- a description
- maintainer(s)

So we need a mechanism for passing this information to `build_tarballs`. Some possibilities:
1. Add an optional keyword argument `metadata` which takes a `Dict{Symbol,Any}` or so -- easiest to implement, flexible, but also harder to sanitize
2. Add a fixed list of KW args, e.g. `maintainers::Vector{String} = String[], desc::String = "", homepage::String = "", license::String = ""` -- also simple, less flexible, but also easier to use (arguable)
3. Add a `struct PackageMetadata` with all this info, but perhaps also space for other entries -- more complex, easy to use for common cases, could still allow for arbitrary package specific keys

What do people prefer? Other suggestions?

Once these two pieces are in place, we can build tooling atop them, for example:
- add some of the metadata into the generated README
- add a JLL wrapper function for accessing the metadata of a JLL
- add code which queries existing JLLs for e.g. build dependencies and uses these automatically in a builder recipe (e.g. a function `add_recursive_build_deps(deps::Vector)`)

**Comment by jeremiahpslewis** [comment]
@fingolfin 

> Does that seem OK? Is JSON fine? If not what else? Should the file be called something else?

What do you think about using TOML? Looking at the `*_jll` repos it seems like that is the dominant metadata file format, but I may be missing something.

**Comment by giordano** [comment]
That's because Julia itself comes with a TOML reader and not a JSON one.  I'm not sure which one is the best for this use case, BinaryBuilder already requires a JSON reader, so we can choose either.

**Comment by giordano** [comment]
> Does that seem OK? Is JSON fine? If not what else?

Ok, I finally found some time to look at your question after all Rust juggling these days.  I think JSON is fine, this file is probably going to be consumed mainly by BinaryBuilder itself.

> Should the file be called something else?

I'm not sure it should be the same file we currently use to serialise build information on Yggdrasil, even though it can use the existing serialisation mechanisms.  I just don't have a strong opinion on this.

> Next, we need to get the data: Some of it we can fill in automatically:
> - BB version+gitsha used for build
> - hash of source build recipe
> - Source URLs
> - list of all products, for all platforms, with the name with which we dlopen it
> - list of BuildDependencys (per platform, even if the same for all platforms), presumably including version/compat restrictions
> - version number of toolchains

Version number of the toolchains is a bit complicated because [BBB does a lot work](https://github.com/JuliaPackaging/BinaryBuilderBase.jl/blob/f3483151d0a5ab7d4e97fa96c436a63915186740/src/Rootfs.jl#L419-L480) to choose the right version of the toolchain.  We can probably query that function, it's just some extra work though.  I'd include _all_ target dependencies, build and runtime (not `HostBuildDependency`, those are generally only needed to build that package, not to link to it), above I mentioned `BuildDependencies` explicitly because there is no other way to get them.

> Some must be provided by the user / passed to `build_tarballs`
> - license, e.g. an SPDX identifier
> - upstream homepage
> - a description
> - maintainer(s)

Yes, looks good.

> So we need a mechanism for passing this information to `build_tarballs`. Some possibilities:
> 1. Add an optional keyword argument `metadata` which takes a `Dict{Symbol,Any}` or so -- easiest to implement, flexible, but also harder to sanitize
> 2. Add a fixed list of KW args, e.g. `maintainers::Vector{String} = String[], desc::String = "", homepage::String = "", license::String = ""` -- also simple, less flexible, but also easier to use (arguable)
> 3. Add a `struct PackageMetadata` with all this info, but perhaps also space for other entries -- more complex, easy to use for common cases, could still allow for arbitrary package specific keys

I'd go with 3, I think it's the best way forward: I don't want to add dozens of argument to `build_tarballs`, one thing which bundles everything is better, IMHO.

> Once these two pieces are in place, we can build tooling atop them, for example:
> - add some of the metadata into the generated README
> - add a JLL wrapper function for accessing the metadata of a JLL
> - add code which queries existing JLLs for e.g. build dependencies and uses these automatically in a builder recipe (e.g. a function `add_recursive_build_deps(deps::Vector)`)

That'd be awesome, yes!  It doesn't have to happen all at the same time, but those are the goals, yes.

**Comment by giordano** [comment]
Other useful things to collect:

* upstream version number as a string (it may be different from the version of the JLL package).  This would be useful towards https://github.com/JuliaPackaging/Yggdrasil/issues/3774
* anything that is needed to generate the README file.  At the moment every `build_jll_package` call would rewrite it, so the last one would write the final README with the information it has.  This would be useful towards #823.  We'd probably need to revise how we write the README, maybe it should be done by a separate function which reads all information in the final JSON file which accumulates the info from potentially multiple `build_tarballs()` calls.

**Comment by mbauman** [comment]
In order to semi-automated-ly identify CVEs that might apply to JLLs we redistribute, there are a number of metadata things that would be helpful:

* An "upstream project" identifier.  A canonical project name like `libpng` or `OpenSSL` or `cairo`.  This identifier should have its own metadata, including:
    * Project homepage URL
    * A "vendor" or "org" name
    * An NVD CPE, if available
    * The versioning "flavor" — SemVer or otherwise
    * Then maybe additional keywords or _anti-keywords_ or _anti-CPEs_. For example [raptor_jll](https://github.com/JuliaBinaryWrappers/raptor_jll.jl) is _not_ [cpe:2.3:a:librdf:raptor](https://nvd.nist.gov/products/cpe/detail/1586703?namingFormat=2.3&orderBy=CPEURI&keyword=raptor&status=FINAL) or [cpe:2.3:a:symantec:raptor_firewall](https://nvd.nist.gov/products/cpe/detail/51921?namingFormat=2.3&orderBy=CPEURI&keyword=raptor&status=FINAL) or [cpe:2.3:a:zediious:raptor-web](https://nvd.nist.gov/products/cpe/detail/1534529?namingFormat=2.3&orderBy=CPEURI&keyword=raptor&status=FINAL)
 
Then every registered version of a given package would have information about:

* The upstream project identifiers incorporated, with each having:
    * The exact source URL/repo & hash
    * The exact upstream version string
        * Ideally an official release from the upstream project, with hashes
        * If built from a git commit, it'd be very nice to know which official releases it's "between," but this may not be possible
    * If any patches were included (and a link to them if they were)
* The link to the Yggdrasil build script and builder logs

It's worth noting that I'm actively working on [retrospectively populating](https://github.com/mbauman/AdvisoryDB.jl/blob/cba3b261e94be69e1bbe5e67d35f87ecedd65280/cpe_map.toml) a little bit of this, currently in my skunksworks AdvisoryDB project.

**Comment by mbauman** [comment]
Here's the metadata I've generated for AdvisoryDB.jl:

* A [`jll_metadata.toml`](https://github.com/mbauman/AdvisoryDB.jl/blob/main/jll_metadata.toml) file, which is fully-automatically populated with the sources and products that were provided in Yggdrasil's build script.  There are two big challenges here:
    * The build script only started getting linked from the readme somewhere in 2020.  Versions built prior to this do not have this provenance information.  Those try to find their buildscripts at their typical `/P/Pkg/build_tarballs.jl` location or try to find a build_tarballs with a `name = "Pkg"`. This isn't perfect, but it's close.
    * Actually running the build script is troublesome, even if we're not doing any building, especially for old and complicated build scripts.
    All told, this file contains data for 1569 packages that end with `_jll`.  65 packages are currently missing as they failed to jump one of the two above hurdles; some of these are not binary-builder-built.
* The [`upstream_project_info.toml`](https://github.com/mbauman/AdvisoryDB.jl/blob/main/upstream_project_info.toml) table is a fully-manually-populated table that defines what the names of upstream projects are and how to find them (by, e.g., their git repository(s) or download URL(s)).  In the case of download URLs, this uses regexes that capture the version number.
* These two tables are semi-automatedly combined to form the [`package_components.toml`](https://github.com/mbauman/AdvisoryDB.jl/blob/main/package_components.toml) file, which finally has the thing I need: a *conservative* mapping from a JLL version to the upstream projects that it _directly_ redistributes.  These will then be the suggested versions for automated advisory tagging.  Note that there are choices here that only make sense in the context of such a conservative semi-automated system.  For example, Cairo_jll@1.18.2+1 used a commit between upstream’s 1.18.2 and 1.18.4.  So I consider it to “include” both versions, as I want that automated version tracking to consider vulnerabilities from both the upstream versions to apply by default.

**Comment by mbauman** [comment]
Now, for some reason, I have no absolutely memory of BinaryBuilder's `--meta-json` flag from when I was initially doing this work... and only discovered (or maybe re-discovered?) it recently.  Its output actually contains much of what I need!  And better, by using Yggdrasil's recorded Manifests, I can more reliably retrospectively generate them.

I've also been working to make the data structures within GeneralMetadata.jl more BinaryBuilder-agnostic.  These two things together mean that now the _package_ metadata contains `artifact_url`s and optional `artifact_metadata` fields.  For example, [PCRE2_jll.toml](https://github.com/JuliaRegistries/GeneralMetadata.jl/blob/addd8ceb5a8cb0fdaf90b4be2603d56f585c04cd/metadata/P/PCRE2_jll.toml#L114-L117) contains the table:

```toml
["10.47.0+0"]
artifact_metadata = "artifact_metadata/P/PCRE2_jll/PCRE2-v10.47.0+0.toml"
artifact_urls = ["https://github.com/JuliaBinaryWrappers/PCRE2_jll.jl/releases/download/PCRE2-v10.47.0+0/PCRE2.v10.47.0.aarch64-apple-darwin.tar.gz", "https://github.com/JuliaBinaryWrappers/PCRE2_jll.jl/releases/download/PCRE2-v10.47.0+0/PCRE2.v10.47.0.aarch64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/PCRE2_jll.jl/releases/download/PCRE2-v10.47.0+0/PCRE2.v10.47.0.aarch64-linux-musl.tar.gz", "https://github.com/JuliaBinaryWrappers/PCRE2_jll.jl/releases/download/PCRE2-v10.47.0+0/PCRE2.v10.47.0.aarch64-unknown-freebsd.tar.gz", "https://github.com/JuliaBinaryWrappers/PCRE2_jll.jl/releases/download/PCRE2-v10.47.0+0/PCRE2.v10.47.0.armv6l-linux-gnueabihf.tar.gz", "https://github.com/JuliaBinaryWrappers/PCRE2_jll.jl/releases/download/PCRE2-v10.47.0+0/PCRE2.v10.47.0.armv6l-linux-musleabihf.tar.gz", "https://github.com/JuliaBinaryWrappers/PCRE2_jll.jl/releases/download/PCRE2-v10.47.0+0/PCRE2.v10.47.0.armv7l-linux-gnueabihf.tar.gz", "https://github.com/JuliaBinaryWrappers/PCRE2_jll.jl/releases/download/PCRE2-v10.47.0+0/PCRE2.v10.47.0.armv7l-linux-musleabihf.tar.gz", "https://github.com/JuliaBinaryWrappers/PCRE2_jll.jl/releases/download/PCRE2-v10.47.0+0/PCRE2.v10.47.0.i686-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/PCRE2_jll.jl/releases/download/PCRE2-v10.47.0+0/PCRE2.v10.47.0.i686-linux-musl.tar.gz", "https://github.com/JuliaBinaryWrappers/PCRE2_jll.jl/releases/download/PCRE2-v10.47.0+0/PCRE2.v10.47.0.i686-w64-mingw32.tar.gz", "https://github.com/JuliaBinaryWrappers/PCRE2_jll.jl/releases/download/PCRE2-v10.47.0+0/PCRE2.v10.47.0.powerpc64le-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/PCRE2_jll.jl/releases/download/PCRE2-v10.47.0+0/PCRE2.v10.47.0.riscv64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/PCRE2_jll.jl/releases/download/PCRE2-v10.47.0+0/PCRE2.v10.47.0.x86_64-apple-darwin.tar.gz", "https://github.com/JuliaBinaryWrappers/PCRE2_jll.jl/releases/download/PCRE2-v10.47.0+0/PCRE2.v10.47.0.x86_64-linux-gnu-sanitize+memory.tar.gz", "https://github.com/JuliaBinaryWrappers/PCRE2_jll.jl/releases/download/PCRE2-v10.47.0+0/PCRE2.v10.47.0.x86_64-linux-gnu.tar.gz", "https://github.com/JuliaBinaryWrappers/PCRE2_jll.jl/releases/download/PCRE2-v10.47.0+0/PCRE2.v10.47.0.x86_64-linux-musl.tar.gz", "https://github.com/JuliaBinaryWrappers/PCRE2_jll.jl/releases/download/PCRE2-v10.47.0+0/PCRE2.v10.47.0.x86_64-unknown-freebsd.tar.gz", "https://github.com/JuliaBinaryWrappers/PCRE2_jll.jl/releases/download/PCRE2-v10.47.0+0/PCRE2.v10.47.0.x86_64-w64-mingw32.tar.gz"]
registered = 2025-10-25T17:30:59.000Z
```

It's referencing the artifact metadata in [`artifact_metadata/P/PCRE2_jll/PCRE2-v10.47.0+0.toml`](https://github.com/JuliaRegistries/GeneralMetadata.jl/blob/addd8ceb5a8cb0fdaf90b4be2603d56f585c04cd/artifact_metadata/P/PCRE2_jll/PCRE2-v10.47.0%2B0.toml):

```toml
buildscript = "https://github.com/JuliaPackaging/Yggdrasil/tree/973c58dcc8263db5ba6a524f01420a482a56665a/P/PCRE2/build_tarballs.jl"
metadata_source = "retrospective (by README link)"
system = "Yggdrasil"
version = "0.6.5"

[metadata]
augment_platform_block = ""
init_block = ""
julia_compat = "1.9"
lazy_artifacts = false
name = "PCRE2"
platforms = ["i686-linux-gnu", "x86_64-linux-gnu", "aarch64-linux-gnu", "armv6l-linux-gnueabihf", "armv7l-linux-gnueabihf", "powerpc64le-linux-gnu", "riscv64-linux-gnu", "i686-linux-musl", "x86_64-linux-musl", "aarch64-linux-musl", "armv6l-linux-musleabihf", "armv7l-linux-musleabihf", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-freebsd", "aarch64-unknown-freebsd", "i686-w64-mingw32", "x86_64-w64-mingw32", "x86_64-linux-gnu-sanitize+memory"]
script = """cd $WORKSPACE/srcdir/pcre2*\n\nif [[ ${bb_full_target} == *-sanitize+memory* ]]; then\n    # Install msan runtime (for clang)\n    cp -rL ${libdir}/linux/* /opt/x86_64-linux-musl/lib/clang/*/lib/linux/\nfi\n\n# Force optimization\nexport CFLAGS=\"${CFLAGS} -O3\"\n\n./configure --prefix=${prefix} --build=${MACHTYPE} --host=${target} \\\n    --disable-symvers \\\n    --enable-jit \\\n    --enable-pcre2-16 \\\n    --enable-pcre2-32\n\nmake -j${nproc}\nmake install\n\n# On windows we need libcpre2-8.dll as well\nif [[ ${target} == *mingw* ]]; then\n    ln -s libpcre2-8-0.dll  ${libdir}/libpcre2-8.dll\n    ln -s libpcre2-16-0.dll ${libdir}/libpcre2-16.dll\n    ln -s libpcre2-32-0.dll ${libdir}/libpcre2-32.dll\nfi\n"""
version = "v10.47.0"

    [[metadata.dependencies]]
    compat = ""
    name = "LLVMCompilerRT_jll"
    platforms = ["x86_64-linux-gnu-sanitize+memory"]
    top_level = false
    type = "builddependency"
    uuid = "4e17d02c-6bf5-513e-be62-445f41c75a11"
    version-major = 13
    version-minor = 0
    version-patch = 1

    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libpcre2-8"]
    type = "lib"
    variable_name = "libpcre2_8"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libpcre2-16"]
    type = "lib"
    variable_name = "libpcre2_16"
    [[metadata.products]]
    dir_paths = []
    dlopen_flags = []
    dont_dlopen = false
    libnames = ["libpcre2-32"]
    type = "lib"
    variable_name = "libpcre2_32"

    [[metadata.sources]]
    hash = "47fe8c99461250d42f89e6e8fdaeba9da057855d06eb7fc08d9ca03fd08d7bc7"
    type = "archive"
    unpack_target = ""
    url = "https://github.com/PCRE2Project/pcre2/releases/download/pcre2-10.47/pcre2-10.47.tar.bz2"
```

The `metadata` section here is _exactly_ the `--meta-json`.  The additional fields I've added as its siblings are the BinaryBuilder version (which implicitly is defining the schema of the `metadata`) and a bit of build _system_ metadata.

-----------------

We could significantly improve our provenance information here if Yggdrasil simply uploaded these JSONs alongside its logs as release assets.  Then instead of retrospectively generating them, we'd fetch them directly, as recorded by the system itself.

There are only two (very important) things missing from this structure:

* Upstream component(s) & their versions
* Upstream component license(s)

I think it's worth adding both directly into this artifact metadata toml as top-level fields.  Having these metadata files split out like this makes it easier to manually review and curate... and I still hope we can eventually get humans to more reliably author and review these data directly within the BinaryBuilder/Yggdrasil build process itself.
